party = Mixtape.create(label: "Party Mix vol. 1")
happy = Mixtape.create(label: "Happy Jams")
shower = Mixtape.create(label: "Shower Songs")

s1 = Song.create(name: "Handclap", artist: "Fitz & The Tantrums", duration: 133)
s2 = Song.create(name: "In The End", artist: "Linkin Park", duration: 157)
s3 = Song.create(name: "Dying in LA", artist: "Panic! at the Disco", duration: 169)
s4 = Song.create(name: "The Swiss Army Romance", artist: "Dahsboard Confessional", duration: 126)
s5 = Song.create(name: "Hard Times", artist: "Paramore", duration: 122)
s6 = Song.create(name: "Purple Rain", artist: "Prince", duration: 166)

ms1 = MixtapeSong.create(song: s1, mixtape: party)
ms2 = MixtapeSong.create(song: s6, mixtape: party)
ms3 = MixtapeSong.create(song: s2, mixtape: shower)
ms4 = MixtapeSong.create(song: s3, mixtape: shower)
ms5 = MixtapeSong.create(song: s4, mixtape: shower)
ms6 = MixtapeSong.create(song: s4, mixtape: happy)
ms7 = MixtapeSong.create(song: s6, mixtape: happy)
ms8 = MixtapeSong.create(song: s5, mixtape: happy)