party = Mixtape.create(label: "Party Mix vol. 1")
happy = Mixtape.create(label: "Happy Jams")
shower = Mixtape.create(label: "Shower Songs")

s1 = Song.create(name: "Handclap", artist: "Fitz & The Tantrums", duration: 133)
s2 = Song.create(name: "In The End", artist: "Linkin Park", duration: 157)
s3 = Song.create(name: "Dying in LA", artist: "Panic! at the Disco", duration: 169)
s4 = Song.create(name: "The Swiss Army Romance", artist: "Dahsboard Confessional", duration: 126)
s5 = Song.create(name: "Hard Times", artist: "Paramore", duration: 122)
s6 = Song.create(name: "Purple Rain", artist: "Prince", duration: 166)
s7 = Song.create(name: "Miracle", artist: "illion", duration: 270)
s8 = Song.create(name: "Liability", artist: "Lorde", duration: 171)
s9 = Song.create(name: "RE:", artist: "REOL", duration: 203)
s10 = Song.create(name: "This Side of Paradise", artist: "Hayley Kiyoko", duration: 211)

MixtapeSong.create(song: s1, mixtape: party)
MixtapeSong.create(song: s6, mixtape: party)
MixtapeSong.create(song: s10, mixtape: party)
MixtapeSong.create(song: s8, mixtape: party)
MixtapeSong.create(song: s2, mixtape: shower)
MixtapeSong.create(song: s3, mixtape: shower)
MixtapeSong.create(song: s4, mixtape: shower)
MixtapeSong.create(song: s7, mixtape: shower)
MixtapeSong.create(song: s2, mixtape: shower)
MixtapeSong.create(song: s8, mixtape: shower)
MixtapeSong.create(song: s10, mixtape: shower)
MixtapeSong.create(song: s4, mixtape: happy)
MixtapeSong.create(song: s6, mixtape: happy)
MixtapeSong.create(song: s5, mixtape: happy)